##
# ANOUNCEMENTS BASED ON PERSON SHARONA
##

# SHARONA ALMOST AT HOME
- alias: '[Personen][Sharona] - Bijna thuis'
  trigger:
    - platform: numeric_state
      below: '3'
      entity_id: proximity.home_sharona
  condition:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state_attr('proximity.home_sharona','dir_of_travel','towards') }}"
        - condition: state
          entity_id: person.sharona
          state: 'not_home'
        - condition: state
          entity_id: group.all_devices
          state: 'home'
  action:
    - service: notify.google_home_broadcast
      data:
        message: Sharona arriveert over enkele minuten thuis.


##
# ANOUNCEMENTS BASED ON PERSON PETER
##

# PETER ALMOST AT HOME
- alias: '[Personen][Peter] - Bijna thuis'
  trigger:
    - platform: numeric_state
      below: '3'
      entity_id: proximity.home_peter
  condition:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state_attr('proximity.home_peter','dir_of_travel','towards') }}"
        - condition: state
          entity_id: person.peter
          state: 'not_home'
        - condition: state
          entity_id: group.all_devices
          state: 'home'
  action:
    - service: notify.google_home_broadcast
      data:
        message: Peter arriveert over enkele minuten thuis.

##
# ANOUNCEMENTS GUESTMODE
##

# WELCOME MESSAGE
- alias: '[Personen][Gast] - Welkombericht'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d00034ccb9a_occupancy
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.play_guest_welcome
        state: 'on'
      - condition: state
        entity_id: input_select.house_mode
        state: 'Gast'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.play_guest_welcome
    - service: notify.google_home_broadcast
      data_template:
        message: >-
          Welkom {{ state_attr('calendar.gasten','message') }},
          het is op dit moment {{ states('sensor.time') }},
          het alarmsysteem is uitgeschakeld,
          fijne dag verder, {{ state_attr('calendar.gasten','message') }}.
