####
# SHUTDOWN BEDROOM WHEN EVERYBODY LEAVES
####

- alias: '[Slaapkamer][Presence] - Shutdown bedroom'
  trigger:
    - platform: state
      entity_id: sensor.roompresence_peter
      from: 'Slaapkamer'
    - platform: state
      entity_id: sensor.roompresence_sharona
      from: 'Slaapkamer'
  condition:
    - condition: template
      value_template: "{{ states('sensor.roompresence_peter') != 'Slaapkamer'}}"
    - condition: template
      value_template: "{{ states('sensor.roompresence_sharona') != 'Slaapkamer'}}"
  action:
    - service: script.shutdown_bedroom
