####
# ATTIC - HALLWAY LIGHTS MOTION
####

- alias: '[Zolder][Licht] - Licht aan bij beweging'
  trigger:
    - platform: state
      entity_id: binary_sensor.zolder_overloop_beweging_occupancy
      to: 'on'
  condition:
    - condition: state
      entity_id: light.zolder_overloop_light
      state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.zolder_overloop_light
      brightness: 200

- alias: '[Zolder][Licht] - Licht uit bij inactiviteit'
  trigger:
    - platform: state
      entity_id: binary_sensor.zolder_overloop_beweging_occupancy
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: sensor.roompresence_peter
      from: 'Zolder'
    - platform: state
      entity_id: sensor.roompresence_sharona
      from: 'Zolder'
  condition:
    - condition: state
      entity_id: light.zolder_overloop_light
      state: 'on'
    - condition: template
      value_template: "{{ states('sensor.roompresence_peter') != 'Zolder'}}"
    - condition: template
      value_template: "{{ states('sensor.roompresence_sharona') != 'Zolder'}}"
  action:
    service: light.turn_off
    data:
      entity_id: light.zolder_overloop_light


####
# ATTIC - WASHING LIGHTS DOOR
####

- alias: '[Zolder][Licht] - Licht washok aan bij deur open'
  trigger:
    - platform: state
      entity_id: binary_sensor.zolder_washok_deur_contact
      to: 'on'
  condition:
    - condition: state
      entity_id: light.zolder_washok_light
      state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.zolder_washok_light
      brightness: 200

- alias: '[Zolder][Licht] - Licht uit bij deur dicht'
  trigger:
    - platform: state
      entity_id: binary_sensor.zolder_washok_deur_contact
      to: 'off'
  condition:
    - condition: state
      entity_id: light.zolder_washok_light
      state: 'on'
  action:
    service: light.turn_off
    data:
      entity_id: light.zolder_washok_light
