# FORCE UPDATE OF BSSID
- alias: '[Woonkamer][Presence] - Do presence check'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d00034ccb9a_occupancy
      to: 'on'
  # condition:
  #   - condition: template
  #     value_template: "{{(states('sensor.peter_room_presence') != 'Woonkamer') or (states('sensor.sharona_room_presence') != 'Woonkamer')}}"
  action:
    - service: notify.ios_iedereen
      data:
        message: "request_location_update"
