# FORCE UPDATE OF BSSID
- alias: '[Hal - 1e Verdieping][Presence] - Do presence check'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0004142172_occupancy
      to: 'on'
  # condition:
  #   - condition: template
  #     value_template: "{{(states('sensor.peter_room_presence') != 'Slaapkamer') or (states('sensor.sharona_room_presence') != 'Slaapkamer')}}"
  action:
    - delay:
        seconds: 15
    - service: notify.ios_iedereen
      data:
        message: "request_location_update"
