- alias: '[Hal-Entree][Melding] - Voordeur staat 5 minuten open'
  trigger:
    - platform: state
      entity_id: binary_sensor.hal_entree_voordeur_contact
      to: 'on'
      for:
        minutes: 5
  action:
    - service: notify.ios_iedereen
      data_template:
        title: 'Waarschuwing'
        message: >-
          De voordeur staat al 5 minuten open.
