- alias: '[People][Peter] - Morningroutine with TV'
  initial_state: True
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: PETER_WAKEUP_LIVINGROOMTV
  action:
    - service: script.watch_tv
    - wait_template: "{{ is_state('script.watch_tv','off') }}"
    - service: script.mediacenter_npo1

- alias: '[People][Peter] - Morningroutine with Playlist'
  initial_state: True
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: PETER_WAKEUP_PLAYLIST
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.beneden
        volume_level: 0.6
    - service: spotcast.start
      data:
        entity_id: media_player.beneden
        uri: 'spotify:playlist:37i9dQZF1DWYPwGkJoztcR'
        random_song: true
