- alias: '[People][Sharona] - Coming home'
  initial_state: True
  trigger:
    - platform: state
      entity_id: person.sharona
      to: 'home'
  action:
    - wait_template: "{{ is_state('binary_sensor.hal_entree_voordeur_contact', 'on') }}"
      timeout: "00:15:00"
      continue_on_timeout: 'false'
    - service: notify.mobile_app_iphone_van_sharona
      data_template:
        title: 'Welkom thuis!'
        message: 'Kan ik iets voor je aanzetten?'
        data:
          push:
            category: sharona_cominghome

- alias: '[People][Sharona] - Coming home TV'
  initial_state: True
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SHARONA_COMINGHOME_TV
  action:
    - service: script.watch_tv

- alias: '[People][Sharona] - Coming home playlist'
  initial_state: True
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SHARONA_COMINGHOME_PLAYLIST
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.beneden
        volume_level: 0.6
    - service: spotcast.start
      data:
        entity_id: media_player.beneden
        uri: 'spotify:playlist:37i9dQZF1DWYPwGkJoztcR'
        random_song: true
