##
# AUTOMATIONS FOR SETTING DISHWASHER STATUS
##

# Starting the dishwasher
- alias: '[Appliances][Dishwasher] - Wassen'
  trigger:
    platform: numeric_state
    entity_id: sensor.vaatwasser_current_power
    above: 2
    for:
      seconds: 20
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.vaatwasser_status
        state: 'Inactief'
      - condition: state
        entity_id: input_select.vaatwasser_status
        state: 'Schoon'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.vaatwasser_status
        option: 'Wassen'

# Clean
- alias: '[Appliances][Dishwasher] - Schoon'
  trigger:
    platform: numeric_state
    entity_id: sensor.vaatwasser_current_power
    below: 2
    for:
      minutes: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.vaatwasser_status
        state: 'Wassen'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.vaatwasser_status
        option: 'Schoon'
    - service: script.smart_notify
      data:
        title: 'Vaatwasser'
        message: 'De vaatwasser is klaar.'
        category: "vaatwasser_uitruimen"
        speak: true

# Clear out
- alias: '[Appliances][Dishwasher] - Uitruimen'
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DISHWASHER_CLEANED
  condition:
    - condition: state
      entity_id: input_select.vaatwasser_status
      state: 'Schoon'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.vaatwasser_status
        option: 'Inactief'
