##
# AUTOMATIONS FOR SETTING DRYER STATUS
##

# Washing program started
- alias: '[Appliances][Wasmachine] - Wassen'
  trigger:
    platform: numeric_state
    entity_id: sensor.wasmachine_current_power
    above: 100
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.wasmachine_status
        state: 'Inactief'
      - condition: state
        entity_id: input_select.wasmachine_status
        state: 'Schoon'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.wasmachine_status
      option: 'Wassen'

# Clean
- alias: '[Appliances][Wasmachine] - Schoon'
  trigger:
    platform: numeric_state
    entity_id: sensor.wasmachine_current_power
    below: 5
    for:
      minutes: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.wasmachine_status
        state: 'Wassen'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.wasmachine_status
        option: 'Schoon'
    - service: script.smart_notify
      data:
        title: 'Wasmachine'
        message: 'De wasmachine is klaar.'
        category: "wasmachine_leeghalen"
        speak: true

# Clear out
- alias: '[Appliances][Wasmachine] - Leeghalen'
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: WASHINGMACHINE_CLEARED
  condition:
    - condition: state
      entity_id: input_select.wasmachine_status
      state: 'Schoon'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.wasmachine_status
        option: 'Inactief'
